---
- name: Load OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family }}.yml'
      paths:
        - 'vars'
  tags:
    - always

- name: Add redis repository
  apt_repository:
    repo: ppa:chris-lea/redis-server
  become: yes
  when: ansible_distribution == 'Ubuntu'

- block:

    - name: Install requirements
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ pulp_preq_packages }}"

    - name: Install Redis
      package:
        name: "{{ pulp_redis_package_name }}"
        state: present

    - name: Start Redis
      systemd:
        name: "{{ pulp_redis_server_name }}"
        state: started
        enabled: yes
        daemon_reload: yes

  become: true
