---
pulp_webserver_server: nginx
pulp_content_bind: '127.0.0.1:24816'
pulp_api_bind: '127.0.0.1:24817'
pulp_configure_firewall: auto
pulp_user_home: '/var/lib/pulp'

pulp_webserver_disable_https: false
pulp_webserver_tls_folder: '{{ pulp_config_dir }}'
pulp_webserver_httpd_servername: '{{ ansible_fqdn }}'
