---
- name: Ensure python-cryptography is installed
  package:
    name: '{{ pulp_weberver_python_cryptography }}'
  become: true

- name: Generate CA key
  openssl_privatekey:
    path: '{{ pulp_webserver_tls_folder }}/root.key'

- name: Generate CA CSR
  openssl_csr:
    path: '{{ pulp_webserver_tls_folder }}/root.csr'
    privatekey_path: '{{ pulp_webserver_tls_folder }}/root.key'
    common_name: '{{ ansible_fqdn }}'
    organization_name: Pulp
    country_name: US
    basic_constraints: 'CA:TRUE'

- name: Generate CA certificate
  openssl_certificate:
    path: '{{ pulp_webserver_tls_folder }}/root.crt'
    csr_path: '{{ pulp_webserver_tls_folder }}/root.csr'
    privatekey_path: '{{ pulp_webserver_tls_folder }}/root.key'
    provider: selfsigned

- name: Generate private keys
  openssl_privatekey:
    path: '{{ pulp_webserver_tls_folder }}/pulp_webserver.key'

- name: Generate CSRs standalone
  openssl_csr:
    path: '{{ pulp_webserver_tls_folder }}/pulp_webserver.csr'
    privatekey_path: '{{ pulp_webserver_tls_folder }}/pulp_webserver.key'
    common_name: '{{ ansible_fqdn }}'
    subject_alt_name: 'DNS:{{ ansible_fqdn }}'
    key_usage:
      - keyEncipherment
      - dataEncipherment
    extended_key_usage:
      - serverAuth

- name: Generate certificates
  openssl_certificate:
    path: '{{ pulp_webserver_tls_folder }}/pulp_webserver.crt'
    csr_path: '{{ pulp_webserver_tls_folder }}/pulp_webserver.csr'
    privatekey_path: '{{ pulp_webserver_tls_folder }}/pulp_webserver.key'
    provider: ownca
    ownca_path: '{{ pulp_webserver_tls_folder }}/root.crt'
    ownca_privatekey_path: '{{ pulp_webserver_tls_folder }}/root.key'
    ownca_not_after: '+824d'

- name: Cleanup CSR files
  file:
    path: '{{ pulp_webserver_tls_folder }}/{{ item }}'
    state: absent
  loop:
    - root.csr
    - pulp_webserver.csr
